# Generated by Django 5.0.7 on 2024-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_motorcycle_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcyclemodel',
            name='model',
        ),
        migrations.AddField(
            model_name='motorcyclemodeltranslation',
            name='model',
            field=models.CharField(default='xyz', max_length=255, verbose_name='موديل'),
            preserve_default=False,
        ),
    ]
