# Generated by Django 5.0.7 on 2024-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_motorcyclemodel_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcyclemodeltranslation',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='بلد المنشأ'),
        ),
        migrations.AlterField(
            model_name='motorcyclemodeltranslation',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موديل'),
        ),
    ]
