# Generated by Django 5.0.7 on 2024-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_motorcyclemodeltranslation_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcyclemodeltranslation',
            name='country_of_origin',
            field=models.CharField(default='india', max_length=128, verbose_name='بلد المنشأ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorcyclemodeltranslation',
            name='model',
            field=models.CharField(default='xyz', max_length=255, verbose_name='موديل'),
            preserve_default=False,
        ),
    ]
