# Generated by Django 5.0.7 on 2024-07-28 01:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_motorcyclemodeltranslation_country_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('know_us', models.CharField(max_length=255, verbose_name='How did you know us?')),
                ('company_registration', models.FileField(upload_to='', verbose_name='Company Registration')),
                ('message', models.TextField(verbose_name='Message')),
                ('number_required', models.PositiveIntegerField(verbose_name='Number of Motorcycles Required')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('registration_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid registration number (10 digits).', regex='^[0-9]{10}$')], verbose_name='Registration Number')),
                ('country_city', models.CharField(max_length=255, verbose_name='Country/City')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('selected_motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.motorcyclemodel')),
            ],
        ),
    ]
